name: Export Windows

on:
  push:

jobs:
  Export:
    name: Export Windows
    runs-on: ubuntu-latest

    steps:
    - name: Downloading Commit
      uses: actions/checkout@v4

    - name: Exporting Project
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_mono_export_templates.tpz
        cache: true
        export_debug: true
        relative_project_path: ./
        relative_export_path: ./export/Windows

    - name: Coping Necessary files into the Build
      run: |
        cp -r "Sapato" "export/Windows/Windows Desktop"

    - name: Deploying New Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Maracuja-Engine
        path: export/Windows